apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - image: neo4j:3.4
          name: neo4j
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j
                  key: auth
          ports:
            - containerPort: 7474
              name: browser
            - containerPort: 7687
              name: bolt
          volumeMounts:
            - name: neo4j-persistent-storage
              mountPath: /data
      volumes:
        - name: neo4j-persistent-storage
          persistentVolumeClaim:
            claimName: neo4j-volumeclaim
