apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j-fe
  name: neo4j-fe
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 7474
      name: browser
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app: neo4j